language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer update --dev

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src
  - ./vendor/bin/phpunit --configuration ./phpunit.xml.dist
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
